version: "3.3"

services:
  json:
    image: williamyeh/json-server:latest # for AMD64/x86 pc
    # image: masumonline/arm64-jsonserver:latest #for ARM64 pc
    ports:
      - "8080:3000"
    volumes:
      - ./src:/data
    command:
         --watch db.json
    networks:
      - json

networks:
  json:
